import { MarkingSchemaProvider } from "./MarkingSchemaContext";
import NavBar from "./NavBar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="min-h-screen flex flex-col">
      <body
        suppressHydrationWarning={true}
        className={inter.className + " flex-1 bg-[#1B1D20]"}
      >
        <MarkingSchemaProvider>
          <NavBar />
          {children}
        </MarkingSchemaProvider>
      </body>
    </html>
  );
}
