import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="min-h-screen flex flex-col">
      <body
        suppressHydrationWarning={true}
        className={inter.className + " flex-1"}
      >
        <div className="navbar bg-base-100">
          <div className="flex-1">
            <a className="btn btn-ghost normal-case text-xl">
              CS6080 - Marking App
            </a>
          </div>
          <div className="flex-none">
            <input type="file" className="file-input w-full max-w-xs" />
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
